### ISSUE TITLE
Intro para to PEI's status is incorrect

### ISSUE THREAD

**Issue by brianbancroft** [brianbancroft/OpenCanadaGeoData#5]
https://twitter.com/ruk/status/811366477546868738

**Comment by brianbancroft** [comment]
Specifically, PEI has had skin in the Geo game as far as a decade ago. The difference is that they only recently went to a "open-by-default" philosophy, and quietly.

**Comment by reinvented** [comment]
PEI also, to its credit, recently removed a cumbersome need to agree to a license agreement before each and every GIS data download. 

Also worthy of note is that [PEI civic address data](http://www.gov.pe.ca/civicaddress/download/index.php3) – which covers the entire Island, every property – has been open since the civic addressing system was [established in 2001](http://www.gov.pe.ca/publications/getpublication.php3?number=536).

**Comment by brianbancroft** [comment]
Hi @reinvented, thanks again for bringing this up! I think this has been resolved?
